using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Media.DBContext.Models;

/// <summary>
/// Represents the available albums in the records.
/// </summary>
[Table("albums")]
public class Album
{
  /// <summary>
  /// Primary Key of the album. Autogenerated.
  /// </summary>
  [Key]
  public Guid AlbumId { get; set; }

  /// <summary>
  /// The name of the album
  /// </summary>
  public string AlbumName { get; set; } = null!;

  /// <summary>
  /// The front cover of album.
  /// </summary>
  public string? Cover { get; set; }

  /// <summary>
  /// List of records, which belong to the album.
  /// </summary>
  public ICollection<Record> Records { get; set; } = new List<Record>();
}
