using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Media.DBContext.Models;

/// <summary>
/// Represents the available genres in records.
/// </summary>
public class Genres
{
  /// <summary>
  /// Primary Key. Autogenerated.
  /// </summary>
  [Key]
  public Guid GenreId { get; set; }

  /// <summary>
  /// Name of the genre.
  /// </summary>
  public string Name { get; set; } = null!;

  /// <summary>
  /// The set bitrate for compression for this genre.
  /// </summary>
  public int? Bitrate { get; set; }

  /// <summary>
  /// The front cover of genre.
  /// </summary>
  public string? Cover { get; set; }

  /// <summary>
  /// List of records, which belong to the genre.
  /// </summary>
  public ICollection<Records> Records { get; set; } = new List<Records>();
}
