using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Media.DBContext.Models
{
  /// <summary>
  /// Represents the available languages in the records.
  /// </summary>
  public class Languages
  {
    /// <summary>
    /// Primary Key of the language. Autogenerated.
    /// </summary>
    [Key]
    public Guid LanguageId { get; set; }

    /// <summary>
    /// The name of the langauge
    /// </summary>
    public string Name { get; set; } = null!;

    /// <summary>
    /// List of records, which belong to the language.
    /// </summary>
    public ICollection<Records> Records { get; set; } = new List<Records>();
  }
}
