using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Media.DBContext.Models;

/// <summary>
/// Represents the available records.
/// </summary>
[Table("records")]
public class Record
{
  /// <summary>
  /// Primary Key. Autogenerated.
  /// </summary>
  [Key]
  public Guid RecordId { get; set; }

  /// <summary>
  /// The path where the file is saved.
  /// </summary>
  [Required]
  public string FilePath { get; set; } = string.Empty;

  /// <summary>
  /// The file checksum
  /// </summary>
  [Required]
  public string Checksum { get; set; } = string.Empty;

  /// <summary>
  /// Mime type of the record. Default Value is audio/mpeg as described in https://www.rfc-editor.org/rfc/rfc3003.
  /// </summary>
  [Required]
  public string MimeType { get; set; } = "audio/mpeg";

  /// <summary>
  /// Title of the record.
  /// </summary>
  [Required]
  public string Title { get; set; } = null!;

  /// <summary>
  /// Date when the record was created.
  /// </summary>
  [Required]
  public DateTime Date { get; set; }

  /// <summary>
  /// The duration of the record.
  /// </summary>
  [Required]
  public TimeSpan Duration { get; set; }

  /// <summary>
  /// The track number of the record.
  /// </summary>
  [Required]
  public int TrackNumber { get; set; }

  /// <summary>
  /// Foreign key to the <see cref="Artists"/> associated with this record or null if unknown.
  /// </summary>
  public Guid? ArtistId { get; set; }
  public Artist? Artist { get; set; }

  /// <summary>
  /// Foreign key to the <see cref="Genres"/> associated with this record or null if unknown.
  /// </summary>
  public Guid? GenreId { get; set; }
  public Genre? Genre { get; set; }

  /// <summary>
  /// Foreign key to the <see cref="Albums"/> associated with this record or null if unknown.
  /// </summary>
  public Guid? AlbumId { get; set; }
  public Album? Album { get; set; }

  /// <summary>
  /// Foreign key to the <see cref="Models.Language"/> associated with this record or null if unknown.
  /// </summary>
  public Guid? LanguageId { get; set; }
  public Language? Language { get; set; }

  /// <summary>
  /// The compressed bitrate of the record. Null if no bitrate was indexed.
  /// </summary>
  public int? Bitrate { get; set; }

  /// <summary>
  /// The front cover of record.
  /// </summary>
  public string? Cover { get; set; }

  /// <summary>
  /// Indicates whether the record is locked.
  /// </summary>
  public bool Locked { get; set; }

  /// <summary>
  /// The groups associated with this record.
  /// </summary>
  public ICollection<Group> Groups { get; set; } = new List<Group>();
}
