using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Media.DBContext.Models;

public class SeedRecords
{
  /// <summary>
  /// Primary Key. Autogenerated.
  /// </summary>
  [Key]
  public Guid RecordId { get; set; }

  /// <summary>
  /// Title of the record.
  /// </summary>
  [Required]
  public string Title { get; set; } = null!;

  /// <summary>
  /// Date when the record was created.
  /// </summary>
  [Required]
  public DateTime Date { get; set; }

  /// <summary>
  /// The duration of the record.
  /// </summary>
  [Required]
  public TimeSpan Duration { get; set; }

  /// <summary>
  /// Foreign key to the <see cref="Artists"/> associated with this record or null if unknown.
  /// </summary>
  public Guid? ArtistId { get; set; }

  /// <summary>
  /// The name of the artist.
  /// </summary>
  public string? ArtistName { get; set; }

  /// <summary>
  /// Foreign key to the <see cref="Genres"/> associated with this record or null if unknown.
  /// </summary>
  public Guid? GenreId { get; set; }

  /// <summary>
  /// Foreign key to the <see cref="Albums"/> associated with this record or null if unknown.
  /// </summary>
  public Guid? AlbumId { get; set; }

  /// <summary>
  /// The id of the next record in order or null if last.
  /// </summary>
  public Guid? NextId { get; set; }

  /// <summary>
  /// The id of the previous record in order or null if first.
  /// </summary>
  public Guid? PreviousId { get; set; }
}
