using System;
using System.ComponentModel.DataAnnotations;

namespace Media.DBContext.Models;

public class SeedRecord
{
  /// <summary>
  /// Primary Key. Autogenerated.
  /// </summary>
  [Key]
  public Guid RecordId { get; set; }

  /// <summary>
  /// Title of the record.
  /// </summary>
  [Required]
  public string Title { get; set; } = null!;

  /// <summary>
  /// Track number of the record.
  /// </summary>
  [Required]
  public int TrackNumber { get; set; }

  /// <summary>
  /// Date when the record was created.
  /// </summary>
  [Required]
  public DateTime Date { get; set; }

  /// <summary>
  /// The duration of the record.
  /// </summary>
  [Required]
  public TimeSpan Duration { get; set; }

  /// <summary>
  /// The bitrate of the record.
  /// </summary>
  public int? Bitrate { get; set; }

  /// <summary>
  /// Cover of the record.
  /// </summary>
  public string? Cover { get; set; }

  /// <summary>
  /// The file checksum
  /// </summary>
  [Required]
  public string Checksum { get; set; } = string.Empty;

  /// <summary>
  /// Foreign key to the <see cref="Artists"/> associated with this record or null if unknown.
  /// </summary>
  public Guid? ArtistId { get; set; }

  /// <summary>
  /// The name of the artist.
  /// </summary>
  public string? ArtistName { get; set; }

  /// <summary>
  /// Foreign key to the <see cref="Genres"/> associated with this record or null if unknown.
  /// </summary>
  public Guid? GenreId { get; set; }

  /// <summary>
  /// The name of the genre.
  /// </summary>
  public string? GenreName { get; set; }

  /// <summary>
  /// Foreign key to the <see cref="Albums"/> associated with this record or null if unknown.
  /// </summary>
  public Guid? AlbumId { get; set; }

  /// <summary>
  /// The name of the album.
  /// </summary>
  public string? AlbumName { get; set; }

  /// <summary>
  /// Foreign key to the <see cref="Language"/> associated with this record or null if unknown.
  /// </summary>
  public Guid? LanguageId { get; set; }

  /// <summary>
  /// The name of the language.
  /// </summary>
  public string? LanguageName { get; set; }

  /// <summary>
  /// The id of the next record in order or null if last.
  /// </summary>
  public Guid? NextId { get; set; }

  /// <summary>
  /// The id of the previous record in order or null if first.
  /// </summary>
  public Guid? PreviousId { get; set; }
}
