using System;
using System.ComponentModel.DataAnnotations;

namespace Media.DBContext.Models;

/// <summary>
/// Represents settings for records.
/// </summary>
public class Setting
{
  /// <summary>
  /// Primary Key. Autogenerated.
  /// </summary>
  [Key]
  public Guid SettingId { get; set; }

  /// <summary>
  /// Unique key of the settings.
  /// </summary>
  [Required]
  public string Key { get; set; } = null!;

  /// <summary>
  /// Settings value.
  /// </summary>
  [Required]
  public string Value { get; set; } = null!;
}
