using Media.Application.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Media.API.Contracts
{
  public class LivestreamChangeRequest(Guid? recordId, string title, string? url, ICollection<Group> groups)
  { /// <summary>
    /// Primary Key. Autogenerated.
    /// </summary>
    public Guid? RecordId { get; set; } = recordId;

    /// <summary>
    /// Name to be displayed.
    /// </summary>
    [Required(ErrorMessageResourceName = nameof(Resources.ValidationMessages.Required), ErrorMessageResourceType = typeof(Resources.ValidationMessages))]
    public string Title { get; set; } = title;

    /// <summary>
    /// The internal url of the streaming provider endpoint.
    /// </summary>
    public string? Url { get; set; } = url;

    /// <summary>
    /// List of groups the record is assigned to.
    /// </summary>
    public ICollection<Group> Groups { get; set; } = groups ?? [];
  }
}
