using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Media.Application.Models
{
  public class LivestreamSettings
  {
    /// <summary>
    /// Primary Key. Autogenerated.
    /// </summary>
    public Guid RecordId { get; set; }

    /// <summary>
    /// Name to be displayed.
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// The internal url of the streaming provider endpoint.
    /// </summary>
    public string? Url { get; set; }

    /// <summary>
    /// The type of the streaming provider endpoint.
    /// </summary>
    public int ProviderType { get; set; }

    /// <summary>
    /// List of groups the livestream is assigned to.
    /// </summary>
    public ICollection<Group> Groups { get; set; }

    public LivestreamSettings()
    {
      Groups = new List<Group>();
    }
  }
}
