using System;
using System.Collections.Generic;

namespace Media.Application.Models;

public class Livestream
{
  /// <summary>
  /// Primary Key. Autogenerated.
  /// </summary>
  public Guid RecordId { get; set; }

  /// <summary>
  /// Name to be displayed.
  /// </summary>
  public string Title { get; set; } = string.Empty;

  /// <summary>
  /// List of groups the livestream is assigned to.
  /// </summary>
  public ICollection<Group> Groups { get; set; }

  public Livestream()
  {
    Groups = new List<Group>();
  }
}
